repos:
  - repo: https://github.com/vikasbharani/vickydec.git 
    rev: v1.0.0
    hooks:
      - id: trailing-whitespaces
      - id: check-json
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=120] 
